# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catsts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='演员名')),
                ('img', models.CharField(max_length=150, verbose_name='演员图片')),
            ],
            options={
                'db_table': 'catsts',
            },
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remen_info', models.CharField(max_length=7000, verbose_name='电影信息')),
            ],
            options={
                'db_table': 'movie_info',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_name', models.CharField(max_length=100, verbose_name='最新榜')),
                ('k_name', models.CharField(max_length=50, verbose_name='口碑榜')),
                ('p_name', models.CharField(max_length=50, verbose_name='票房榜')),
            ],
            options={
                'db_table': 'rank',
            },
        ),
        migrations.CreateModel(
            name='TeleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_info', models.CharField(max_length=7000, verbose_name='电视信息')),
            ],
            options={
                'db_table': 'tele_info',
            },
        ),
    ]
