# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='k_id',
            field=models.CharField(default=1, max_length=50, verbose_name='口碑榜id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rank',
            name='p_id',
            field=models.CharField(default=1, max_length=50, verbose_name='票房榜id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rank',
            name='x_id',
            field=models.CharField(default=1, max_length=50, verbose_name='最新榜id'),
            preserve_default=False,
        ),
    ]
