# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-13 03:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_collectcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_collect', to=settings.AUTH_USER_MODEL, verbose_name='点赞者'),
        ),
    ]
