# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-20 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_starcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_title', models.CharField(max_length=150, verbose_name='新闻名')),
                ('n_url', models.CharField(max_length=150, verbose_name='新闻链接')),
                ('rank_news_title', models.CharField(max_length=150, verbose_name='排行新闻名')),
                ('rank_news_url', models.CharField(max_length=150, verbose_name='排行新闻链接')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
