# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-20 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_news_title', models.CharField(max_length=150, verbose_name='排行新闻名')),
                ('rank_news_url', models.CharField(max_length=150, verbose_name='排行新闻链接')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '新闻排名',
                'verbose_name_plural': '新闻排名',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='rank_news_title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='rank_news_url',
        ),
    ]
