# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-20 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20190820_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ranknews',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
