# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-20 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20190820_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.CharField(max_length=100, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='ranknews',
            name='create_date',
            field=models.CharField(max_length=100, verbose_name='时间'),
        ),
    ]
